beanft/beanftsite/core/views.py
from flask import render_template,request,Blueprint
from beanftsite.models import FileContents

core = Blueprint('core',__name__)

@core.route('/')
def index():

    return render_template('index.html')

beanft/beanftsite/uploader/views.py
from flask import render_template, abort, url_for, flash, redirect, request, Blueprint, Response, session, jsonify, make_response
from flask_bootstrap import Bootstrap
from flask_login import current_user, login_required
from beanftsite import db
from beanftsite.models import FileContents, ModelType, ListXY, factorise_data, convert_df_integer_to_numeric, convert_array_integer_to_numeric
from werkzeug.utils import secure_filename
import os
import urllib.request
import pandas as pd
import numpy as np
import io
import base64
import random
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from sqlalchemy import event, Column, Integer, String, create_engine

# ML Packages 
## Categorical
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier

## test api
import requests
import json
import pickle
import pylint
import warnings
warnings.filterwarnings('ignore')

## Regression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn import linear_model
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler, LabelEncoder



# Configuration settings
uploader = Blueprint('uploader', __name__)
basedir = os.path.abspath(os.path.dirname(__name__))
folder = os.path.abspath(basedir + str('\\beanftsite\\static\\data_uploads\\'))
ALLOWED_EXTENSIONS = set(['csv'])


# Core code
@uploader.route('/uploads', methods=['GET', 'POST'])
def uploads():
    return render_template('uploads.html')

@uploader.route('/train', methods=['GET', 'POST'])
def train():
    if request.method == 'POST' and 'inputFiles' in request.files:
        file = request.files['inputFiles']
        filename = secure_filename(file.filename)
        data_reload = FileContents(name=filename)
        db.create_all()
        db.session.add(data_reload)
        db.session.commit()
        data_reloaded = FileContents.query.all()
        # os.path.join is used so that paths work in every operating system
        file.save(os.path.join(folder,filename))
        # Data review
        new_data = pd.read_csv(os.path.join(folder,str(data_reloaded[-1])))
        new_dataplot = new_data.head(10)
        new_data_info = new_data.info
        new_data_size = new_data.size
        new_data_shape = new_data.shape
        dropdown_list = list(new_data.columns)
        flash('Just a moment, app is thinking!')

        if str(data_reloaded[-1]).split('.')[-1] != 'csv':
            # Forbidden, No Access
            abort(403)
    return render_template('train.html',
        new_dataplot = new_dataplot,
        data_reload = data_reload,
        new_data_info = new_data.info,
        new_data_size=new_data_size,
        new_data_shape=new_data_shape,
        dropdown_list=dropdown_list
        )


@uploader.route('/fit', methods=['GET', 'POST'])
def fit():
    # X and Y vars
    y_var_select = request.form.get('y_var')
    multiselect = request.form.getlist('x_vars')

    # Type of forecast
    pred_type_select = request.form.get('rd_pred_type')
    
    # commit the prediction type
    pred_type_selected = ModelType(pred_type_select)
    db.create_all()
    db.session.add(pred_type_selected)

    # commit the X and Y vars
    xy_selection = ListXY(y_var_select,multiselect)
    db.create_all()
    db.session.add(xy_selection)
    db.session.commit()

    # testing - DELETE AFTEWARDS
    ListXY.query.all()

    # select vars
    data_reloaded = FileContents.query.all()
    new_data = pd.read_csv(os.path.join(folder, str(data_reloaded[-1])))
    new_data = new_data.dropna() # deletes Na and NaN
    X = new_data[multiselect]
    Y = new_data[y_var_select]

    if request.form.get('rd_pred_type') == "Classification":
        # Step 1: Refactor columns with text to integer and remove NAs
        X = factorise_data(X)

        # prepare models
        seed = 7
        models = []
        models.append(('RandomForestClassifier', RandomForestClassifier()))
        models.append(('GradientBoostingClassifier', GradientBoostingClassifier()))
        models.append(('LogisticRegression', LogisticRegression()))
        models.append(('LinearDiscriminantAnalysis', LinearDiscriminantAnalysis()))
        models.append(('KNeighborsClassifier', KNeighborsClassifier()))
        models.append(('GaussianNB', GaussianNB()))
        models.append(('SVC', SVC()))
        # evaluate each model in turn
        results = []
        names = []
        allmodels = []
        scoring = 'accuracy'
        for name, model in models:
            kfold = model_selection.KFold(n_splits=10, random_state=seed)
            cv_results = model_selection.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
            results.append(cv_results)
            names.append(name)
            msg = "%s - %f | %f" % (name, cv_results.mean(), cv_results.std())
            allmodels.append(msg)
            model_results = results
            model_names = names


    if request.form.get('rd_pred_type') == "Regression":
        # Step 1: Refactor columns with text to integer and remove NAs
        X = factorise_data(X)

        # prepare models
        models = []
        models.append(('RandomForestRegressor', RandomForestRegressor(n_estimators=200)))
        models.append(('GradientBoostingRegressor', GradientBoostingRegressor(n_estimators=200)))
        models.append(('Ridge', Ridge()))
        models.append(('ElasticNet', ElasticNet()))
        models.append(('Lasso', Lasso()))
        models.append(('SVR', SVR()))
        # evaluate each model in turn
        results = []
        names = []
        allmodels = []
        for name, model in models:
            X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3, random_state = 7)
            # standard scaler #standardises the feature variables
            sc = StandardScaler()
            X_train = sc.fit_transform(X_train)
            X_test = sc.transform(X_test)
            model_to_fit = model
            model_to_fit.fit(X_train, y_train)
            predictions = model_to_fit.predict(X_test)
            mse = mean_squared_error(y_test, predictions)
            results.append(mse)
            names.append(name)
            msg = "%s - %.2f | %s" % (name, (np.sqrt(mse)), "-")
            allmodels.append(msg)
            model_results = results
            model_names = names

    return render_template('fit.html',y_var_select=y_var_select,
        pred_type_select = pred_type_select,
        multiselect = multiselect, 
        model_results = allmodels,
        model_names = names)


@uploader.route("/predict_data" , methods=['GET', 'POST'])
def predict_data():

    if request.method == 'POST' and 'inputTestFile' in request.files:
        # load selected model type
        selected_model_type = request.form.get('selected_model')
        # load the data to predict on
        testfile = request.files['inputTestFile']
        testfilename = secure_filename(testfile.filename)
        testfile.save(os.path.join(folder,testfilename))

        # load the previously selected prediction type, X and Y vars
        pred_type_select_all = ModelType.query.all()
        x_selected_model = ListXY.query.order_by(ListXY.id.desc()).first().x_vars
        y_selected_model = ListXY.query.order_by(ListXY.id.desc()).first().y_var
        pred_type = str(pred_type_select_all[-1])

        
        # load data again to predict
        data_reloaded = FileContents.query.all()
        data_reloaded_2 = str(data_reloaded[-1])
        new_data = pd.read_csv(os.path.join(folder,str(data_reloaded[-1])))
        new_data = new_data.dropna() # deletes Na and NaN

        X = new_data[eval(x_selected_model)]
        Y = new_data[y_selected_model]

        if pred_type == "Classification":
            # Step 1: Refactor columns with text to integer and remove NAs
            X = factorise_data(X)

            # prepare models
            seed = 7
            models = []
            models.append(('RandomForestClassifier', RandomForestClassifier(n_estimators=200)))
            models.append(('GradientBoostingClassifier', GradientBoostingClassifier(n_estimators=200)))
            models.append(('LogisticRegression', LogisticRegression()))
            models.append(('LinearDiscriminantAnalysis', LinearDiscriminantAnalysis()))
            models.append(('KNeighborsClassifier', KNeighborsClassifier()))
            models.append(('GaussianNB', GaussianNB()))
            models.append(('SVC', SVC()))

            # evaluate each model in turn
            results = []
            names = []
            allmodels = []
            scoring = 'accuracy'
            for name, model in models:
                X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, random_state = 7)
                # standard scaler #standardises the feature variables
                sc = StandardScaler()
                X_train = sc.fit_transform(X_train)
                X_test = sc.transform(X_test)
                if selected_model_type == name:
                    model_to_fit = model
                    model_to_fit.fit(X_train, Y_train)
                    # save model and test api
                    saved_model = os.path.join(folder, str("final_model.sav")) 

beanft/beanftsite/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from beanftsite import db
from werkzeug.security import generate_password_hash,check_password_hash
from beanftsite.models import User, FileContents
from beanftsite.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from beanftsite.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    
    return render_template('user_posts.html', user=user)

beanft/beanftsite/templates/account.html
{% extends "base.html" %}
{% block content %}

<head>
  <div class="large-empty-row">
  </div>
</head>


<body>
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
      <p>{{ current_user.email }}</p>
    </div>
  </div>
  <div class="container">
  </div>
  <br>
  {% if current_user.is_authenticated %}
    <p>You have signed in. Now you can create your model or visualise some data.</p>
    <p><a href="{{ url_for('uploader.uploads')}}" type="button" class="btn btn-primary" >Model</a></p>
    <p><a href="{{ url_for('uploader.plot')}}" type="button" class="btn btn-primary" >Visualise</a></p>
  {% else %}
    <p>If you do not have an account or want to create another account, click the button below.</p>
    <p><a href="{{ url_for('users.register')}}" type="button" class="btn btn-primary" >Register</a></p>
  {% endif %}
</body>

{% endblock content %}

beanft/beanftsite/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" />
    <link rel="stylesheet" media="screen" href = "{{ url_for('static', filename='bootstrap.min.css') }}">
    

    <!-- <link rel="stylesheet" href="../static/main.css') }}" /> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <title>Welcome to Bean Forecast Tool! Your one stop machine learning app.</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="{{ url_for('core.index') }}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-link"><a class="nav-link" href="{{ url_for('users.account') }}">Account <span class="sr-only">(current)</span></a>
        </li>
    {% if current_user.is_authenticated %}
    <!-- <ul class="navbar-nav"> -->
        <li class="nav-link"><a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
        <li class="nav-link"><a class="nav-link" href="{{ url_for('uploader.uploads') }}">Upload</a></li>
        <li class="nav-link"><a class="nav-link" href="{{ url_for('uploader.plot') }}">Plot</a></li>
    <!-- </ul> -->
    {% else %}
    <!-- <ul class="navbar-nav"> -->
        <li class="nav-link"><a class="nav-link" href="{{ url_for('users.login') }}">Log In</a></li>
        <li class="nav-link"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a></li>
    <!-- </ul> -->
    {% endif %}
      </ul>
    </div>
  </nav>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

beanft/beanftsite/templates/chart.html
{% extends "base.html" %}
{% block content %}

<div class ="large-empty-row">
</div>

<head>
  <meta charset="utf-8" />
  <title>Chart.js Example</title>
  <!-- import plugin script -->
  <script src='static/Chart.min.js'></script>
</head>
<body>
  <h2>The chart is displaying a simple scatter plot</h2>
  <!-- bar chart canvas element -->
  <canvas id="myChart" width="600" height="400"></canvas>
  <div class ="large-empty-row">
  </div>
  <p id="caption">On your x axis is "{{  x_axis_select_str }}"</p>
  <p id="caption">On your y axis is "{{  y_axis_select_str }}"</p>

  <script>
    // Global parameters:
    // do not resize the chart canvas when its container does (keep at 600x400px)
    Chart.defaults.global.responsive = false;

    // define the chart data
    var chartData = {
      labels : [{% for item in labels %}
                  "{{item}}",
                {% endfor %}],
      datasets : [{
          label: '{{  y_axis_select_str }}',
          fill: false,
          lineTension: 0,
          backgroundColor: "rgba(75,192,192,0.4)",
          borderColor: "rgba(75,192,192,1)",
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: "rgba(75,192,192,1)",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(75,192,192,1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          pointRadius: 2,
          pointHitRadius: 2,
          showLine: false,
          data: [{% for vals in values %}
                  "{{vals}}",
                {% endfor %}]
      }]
    }

    // get chart canvas
    var ctx = document.getElementById("myChart").getContext("2d");

    // create the chart using the chart canvas
    var myChart = new Chart(ctx, {
      type: 'line',
      data: chartData,
      // options: {
      //   scales: {
      //     xAxes: [{
      //         type: 'linear',
      //         position: 'bottom'
      //     }]
      //   }
      // }
    });
  </script>

</body>

{% endblock %}

beanft/beanftsite/templates/fit.html
{% extends "base.html" %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" /> -->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>



<div class="large-empty-row">
</div>

<body>

    <title>Fit my Model</title>
    <div class="alert alert-danger" role="alert" >
      <p>This is a {{ pred_type_select }} type prediction. You are predicting <span style="color:rgb(255, 0, 0)">{{ y_var_select }}</span> against the following predictor variables.</p>
    </div>
    <div class="alert alert-info" role="alert" style="background-color:#e6e7e8;border-color:#d8d9da">
      <p><span style="color:rgb(0, 0, 0)">Predictor variables: </span>
      <ul class = "csv">
        {% for column in multiselect %}
          <li>{{ column }}</li>
        {% endfor %}
      </ul>
      </p>
    </div>
    <div class="empty-row">
    </div>  
    <h2>Model Score</h2>
    <div class="col_ms">
      {% for mlaccuracy  in model_results %}
      <div class="list-group">
          <a href="#" class="list-group-item" style="background-color:#e6e7e8">
            <span style="color:rgb(0, 0, 0)">ML Algorithm - Performance Metrics (Mean R<sup>2</sup>/RMSE) | Mean Standard Deviation</span></a>
          <a href="#" class="list-group-item">{{ mlaccuracy }}</a>
      </div>
      <br>
      {% endfor %}
    </div>

    <div class="large-empty-row">
    </div>

    <form method="post" action="/predict_data" enctype="multipart/form-data">
      <div>
        <span class="input-group-addon">Which of these models would you like to use?</span><br>
        <select name="selected_model" class="selectpicker form-control">
          {% for model in model_names %}
          <option value= "{{ model }}" SELECTED>{{ model }}</option><br>
          {% endfor %}
        </select>
      </div>    
    
      <div class="large-empty-row">
      </div>
    
      <div>
        <span class="input-group-addon">Select file to predict with.</span><br>
        <p>
          <dl>
              <p>
                  <input type="file" name="inputTestFile" multiple="true" autocomplete="off" required>
              </p>
          </dl>
          <br>
          <input type="submit"  class="btn btn-primary" value="Save predicted data">
        </p>
      </div>
    </form>

</body>

{% endblock %}

beanft/beanftsite/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="large-empty-row">
  </div>
  <div class="jumbotron">
    <h1>Bean Forecast Tool</h1>
    <p>Basic machine learning tool automated for predicting, exploring and visualising data.</p>
  </div>
<body>
  <p>To upload your data and predict with the forecast tool, create an account or log in by clicking the button below</p>
  <p><a href="{{ url_for('users.account')}}" type="button" class="btn btn-primary" > Go to Account</a></p>
</body>
{% endblock %}

beanft/beanftsite/templates/login.html
{% extends "base.html" %}
{% block content %}

<head>
    <div class="large-empty-row">
    </div>
</head>

<body>
    <p>You are almost there, simply login or create an account to access the bean forecast tool and more.</p>
    <form method="POST">
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.hidden_tag() }}
        {{ form.email.label }} {{ form.email() }}
        <br>
        {{ form.password.label }} {{ form.password() }}
        <br>
        {{ form.submit() }}
        <div class="large-empty-row">
        </div>
        <p>
            If you do not have an account, click <a href="{{ url_for('users.register')}}">here</a> to create one.
        </p>
    </form>
</body>

{% endblock %}

beanft/beanftsite/templates/plot.html
{% extends "base.html" %}
{% block content %}

<div class="large-empty-row">
</div>

<title>Only line plots are available. Line plots are best applied on numerical data.</title>
<h2>Select file to upload for plotting.</h2>
<p>
    <form method="post" action="/plot_2" enctype="multipart/form-data">
        <dl>
            <p>
                <input type="file" name="inputFiles" multiple="true" autocomplete="off" required>
            </p>
        </dl>
        <br>
        <input type="submit"  onclick="myAnalyser()" class="btn btn-primary" value="Submit">
    </form>
</p>
{% endblock %}

beanft/beanftsite/templates/plot_2.html
{% extends "base.html" %}
{% block content %}

<div class ="large-empty-row">
</div>

<body>
  <h2>Select the columns you want visualised below:</h2>
  <form class="form-inline" action="/graph" method="POST" id = "my_form_id">
    <div class="form-group">
      <div class="input-group_y">
      <span class="input-group-addon">Select "x" column</span> <br>
        <select name="select_x" class="selectpicker form-control">
          {% for column in dropdown_list %}
          <option value= "{{ column }}" SELECTED>{{ column }}</option><br>
          {% endfor %}
        </select>
      </div>
      <div class ="empty-row">
      </div>
      <div class="input-group_x">
        <span class="input-group-addon">Select "y" column </span><br>
          <select name="select_y" class="selectpicker form-control">
            {% for column in dropdown_list %}
            <option value= "{{ column }}" SELECTED>{{ column }}</option><br>
            {% endfor %}
          </select>
      </div>
      <div class ="empty-row">
      </div>
      <input type="submit"  onclick="myAnalyser()" class="btn btn-primary" value="Submit">
    </div>
  </form>
</body>
{% endblock %}

beanft/beanftsite/templates/plot_3.html
{% extends "base.html" %}
{% block content %}

<div class ="large-empty-row">
</div>
<h2>Right click and save plot or click "Plot" to select new fields to plot. Reloading the page will break the app.</h2>
<br>
<p>On your x axis is "{{  x_axis_select_str }}"</p>
<p>On your y axis is "{{  y_axis_select_str }}"</p>
<body>
  <div style = "width:50%; float:left">
    <img src="data:image/png;base64, {{ plot_url }}">
  </div>
</body>

{% endblock %}

beanft/beanftsite/templates/predict_data.html
{% extends "base.html" %}
{% block content %}

<div class="large-empty-row">
</div>

<div>
    <p>Fit my Model</p>
    <p>This is {{ testfilename }} and {{ my_x_selected_model }} .</p>
    <p>Added this: {{ data }}</p>
    <p>and that: {{ r }}</p>
</div>
 

{% endblock %}

beanft/beanftsite/templates/register.html
{% extends "base.html" %}
{% block content %}

<head>
    <div class="large-empty-row">
    </div>
</head>


<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

beanft/beanftsite/templates/train.html
{% extends "base.html" %}
{% block content %}



<head>
  <meta charset="UTF-8">
  <!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script> -->
</head>

<div class="large-empty-row">
</div>

<body>
  <title>Fit my Model</title>
  <h2>You are predicting using: {{ data_reload }}</h2>
  <br>
  <p>The first 10 rows of your data is previewed in the table below. Scroll down to select your predictor variables and target variable.</p>
  <!-- <div class="alert alert-info" role="alert"><p><span style="color:red">Size</span>: {{ new_data_size }}</p></div>
  <div class="alert alert-info" role="alert"><p><span style="color:red">Information</span>: {{ new_data_info }}</p></div> -->
  <!-- ADD TYPE OF EACH COLUMN -->
  <div class="alert alert-danger" role="alert"><p><span style="color:red">Dimension of uploaded data</span>: <br/>
  (Row,Columns)<br/>
  {{ new_data_shape }}</p></div>

  <br>
  <div id="myDIV" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">
    {{ new_dataplot.to_html(classes="table table-striped table-hover",na_rep="-") | safe}}
  </div>

  <form class="form-inline" method="POST" action="/fit" id = "my_form_id">
    <div class="form-group">
      <div class="input-group_y">
      <span class="input-group-addon">Select y variable </span> <br>
        <select name="y_var" class="selectpicker form-control">
          {% for column in dropdown_list %}
          <option value= "{{ column }}" SELECTED>{{ column }}</option><br>
          {% endfor %}
        </select>
      </div>
      <div class ="empty-row">
      </div>
      <div class="input-group_x">
        <span class="input-group-addon">Select x variables </span><br>
          <select name="x_vars" class="selectpicker form-control" multiple id="mymultiselect">
            {% for column in dropdown_list %}
            <option value= "{{ column }}" SELECTED>{{ column }}</option><br>
            {% endfor %}
          </select>
      </div>
      <div class ="empty-row">
      </div>
      <div class="cat_or_reg">
        <p>Choose prediction type</p>
          <input type="radio" class="form-check-input" name="rd_pred_type"  value="Classification"> Classification
          <br>
          <input type="radio" class="form-check-input" name="rd_pred_type"  value="Regression"> Regression
          <div class= "hint_text">
            <p><em>*Hint: For a regression style model, explanatory variables must contain integers or real numbers. For a categorical model, the predicted variable must consist of less than 6 factors for optimal accuracy.</em></p>
          </div>
      </div>
      <div class ="large-empty-row">
      </div>
      <div class="train_submit_button">
        <input type="submit"  onclick="$('#loading').show();" class="btn btn-primary" value="Submit">
      </div>
    </div>
  </form>

  <div id="loading" style="display:none;"><img src="static/profile_pics/loadingimage.gif" alt="" /><br>Model is thinking!</div>

  <div class ="large-empty-row">
  </div>

</body>

{% endblock %}

beanft/beanftsite/templates/uploads.html
{% extends "base.html" %}
{% block content %}

<div class="large-empty-row">
</div>

<title>Upload your file here</title>
<h2>Select file to upload</h2>
<p>
    <form method="post" action="/train" enctype="multipart/form-data">
        <dl>
            <p>
                <input type="file" name="inputFiles" multiple="true" autocomplete="off" required>
            </p>
        </dl>
        <br>
        <input type="submit"  onclick="myAnalyser()" class="btn btn-primary" value="Submit">
    </form>
</p>
{% endblock %}